
#DISEASECRAFT CONFIG (CLIENT)
#
#Effect rendering will be altered here.
#
#Gameplay options can be found in the common config.
[client]
	#Should diseases be showed below any mob effects?
	#
	#TRUE = Displays diseases in inventory
	#FALSE = Does not display diseases
	#
	#Will become false by default after full release.
	showDiseases = true

