
[General]
	#Allow Fusion loot to be added to chests?
	AddChestLoot = false
	#Enable Fusion aesthetic blocks?
	EnableAestheticsBlocks = false

["Alloy Recipes"]
	#false disables alloy recipes
	EnableSteelMaking = false
	#false disables alloy recipes
	EnableBronzeMaking = false
	#false disables alloy recipes
	EnableSinisiteMaking = false
	#false disables alloy recipes
	EnableThyriumMaking = false

[Tools]
	#false disables recipes
	EnableSteelTools = false
	#false disables recipes
	EnableBronzeTools = true
	#false disables recipes
	EnableSinisiteTools = false
	#false disables recipes
	EnableThyriumTools = false

[Armor]
	#false disables recipes
	EnableSteelArmor = false
	#false disables recipes
	EnableBronzeArmor = true
	#false disables recipes
	EnableSinisiteArmor = false
	#false disables recipes
	EnableThyriumArmor = false

[Bows]
	#false disables recipes
	EnableFusionBows = false

["Simple Fusion Recycling"]
	#Enable Simple Fusion Recycling recipes for vanilla metals?
	enableVanillaRecycling = false
	#Enable Simple Fusion Recycling recipes for Simple Ores?
	enableSimpleOresRecycling = false
	#Enable Simple Fusion Recycling recipes for Netherrocks?
	enableNetherrocksRecycling = false
	#Enable Simple Fusion Recycling recipes for Fusion?
	enableFusionRecycling = false
	#Enable Simple Fusion Recycling recipes for Diamonds/Onyx?
	enableGemRecycling = false

