#The names of the tabs.
tabNames = ["diamond_sword", "cobblestone", "ETC", "Tab 3", "Tab 4", "Tab 5", "Tab 6", "Tab 7", "Tab 8"]
#The names of the screens that tabs should NOT be rendered in.
screensBlacklist = []
#Show the names of the opened screens in chat.
showScreenNames = false

